### ISSUE TITLE
abstract for packages can't be set, resulting in 'a cool package' in all generated modules

### ISSUE THREAD

**Issue by haarg** [rjbs/Module-Faker#15]
There doesn't seem to be a way to set the abstract for a package from the data files. Generated modules always try to add a pod NAME section, with the name and abstract of the first package. Since there is no abstract, it uses 'a cool package' instead.

This behavior also conflicts somewhat with what is in the documentation. An example shows:
```
X_Module_Faker:
  cpan_author: SOMEONE
  append:
    - file: lib/Provides/Inner.pm
      content: "\n=head1 NAME\n\nAppend - here I am"
```
This won't work correctly, because the module will already have a NAME section added with the default abstract.

This behavior was added in e262ce4e40450c0cd0ce7c956115d268bff6d2cc.

On MetaCPAN, we're pinning an older version of Module::Faker to work around the problem. We're doing the same as is shown in the example, adding a pod NAME section using `append`.
